disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - superfluous_disable_command
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods